# frozen_string_literal: true

RSpec.describe Zon::Parser do
    Parser = described_class
    Lexer = Zon::Lexer

    context "parse simple struct" do 

      before do
        @dict = <<~ZON
        .{
          .name = .passkeez,
          .version = "0.5.3",
          .fingerprint = 0xdd1692d15d21a6f6,
        }
        ZON
      end

      it "parses a ZON string into a Ruby object" do
        expected = {
          :name => :passkeez, 
          :version => "0.5.3", 
          :fingerprint => 0xdd1692d15d21a6f6
        }

        tokens = Lexer.parse @dict
        parser = Parser.new tokens

        obj = parser.parse

        expect(obj).to eq(expected)
      end

    end

    context "valid build.zig.zon for packages supporting Zig 0.15.1" do
      before do
        @dict = <<~ZON
        .{
          .name = .passkeez,
          .version = "0.5.3",
          .fingerprint = 0xdd1692d15d21a6f6,
          .dependencies = .{
              .keylib = .{
                  .url = "https://github.com/Zig-Sec/keylib/archive/refs/tags/0.6.1.tar.gz",
                  .hash = "keylib-0.6.1-mbYjk9-WCQBOqB9oq2ZqWQFeWI2HwuBEuPgL-wkJDHTg",
              },
              .uuid = .{
                  .url = "https://github.com/r4gus/uuid-zig/archive/refs/tags/0.3.1.tar.gz",
                  .hash = "uuid-0.3.0-oOieIYF1AAA_BtE7FvVqqTn5uEYTvvz7ycuVnalCOf8C",
              },
              .ccdb = .{
                  .url = "https://github.com/r4gus/ccdb/archive/refs/tags/0.3.1.tar.gz",
                  .hash = "ccdb-0.3.2-mrOGYn4KDgC0cJl4CKpKaJB95wwIlHegHLV7NSbMYXu0",
              },
              .kdbx = .{
                  .url = "https://github.com/Zig-Sec/kdbx/archive/refs/tags/0.1.4.tar.gz",
                  .hash = "kdbx-0.1.4-eJXZBMa7CgAIw7kG02QYyv1sFcePsjfoGH9-Ptl3wrTC",
              },
          },
          .paths = .{
              "build.zig",
              "build.zig.zon",
              "linux",
              "README.md",
              "script",
              "src",
              "static",
          },
        }
        ZON
      end

      it "parses a ZON string into a Ruby object" do
        expected = {
          :name => :passkeez, 
          :version => "0.5.3", 
          :fingerprint => 0xdd1692d15d21a6f6,
          :dependencies => {
            :keylib => {
              :url => "https://github.com/Zig-Sec/keylib/archive/refs/tags/0.6.1.tar.gz",
              :hash => "keylib-0.6.1-mbYjk9-WCQBOqB9oq2ZqWQFeWI2HwuBEuPgL-wkJDHTg",
            },
            :uuid => {
              :url => "https://github.com/r4gus/uuid-zig/archive/refs/tags/0.3.1.tar.gz",
              :hash => "uuid-0.3.0-oOieIYF1AAA_BtE7FvVqqTn5uEYTvvz7ycuVnalCOf8C",
            },
            :ccdb => {
              :url => "https://github.com/r4gus/ccdb/archive/refs/tags/0.3.1.tar.gz",
              :hash => "ccdb-0.3.2-mrOGYn4KDgC0cJl4CKpKaJB95wwIlHegHLV7NSbMYXu0",
            },
            :kdbx => {
              :url => "https://github.com/Zig-Sec/kdbx/archive/refs/tags/0.1.4.tar.gz",
              :hash => "kdbx-0.1.4-eJXZBMa7CgAIw7kG02QYyv1sFcePsjfoGH9-Ptl3wrTC",
            },
          },
          :paths => [
            "build.zig",
            "build.zig.zon",
            "linux",
            "README.md",
            "script",
            "src",
            "static",
          ],
        }

        tokens = Lexer.parse @dict
        parser = Parser.new tokens

        obj = parser.parse

        expect(obj).to eq(expected)
      end

    end

    context "valid build.zig.zon for packages supporting Zig 0.15.1 with comments" do
      before do
        @dict = <<~ZON
        .{
          // This is the default name used by packages depending on this one. For
          // example, when a user runs `zig fetch --save <url>`, this field is used
          // as the key in the `dependencies` table. Although the user can choose a
          // different name, most users will stick with this provided value.
          //
          // It is redundant to include "zig" in this name because it is already
          // within the Zig package namespace.
          .name = .passkeez,
          // This is a [Semantic Version](https://semver.org/).
          // In a future version of Zig it will be used for package deduplication.
          .version = "0.5.3",
          // Together with name, this represents a globally unique package
          // identifier. This field is generated by the Zig toolchain when the
          // package is first created, and then *never changes*. This allows
          // unambiguous detection of one package being an updated version of
          // another.
          //
          // When forking a Zig project, this id should be regenerated (delete the
          // field and run `zig build`) if the upstream project is still maintained.
          // Otherwise, the fork is *hostile*, attempting to take control over the
          // original project's identity. Thus it is recommended to leave the comment
          // on the following line intact, so that it shows up in code reviews that
          // modify the field.
          .fingerprint = 0xdd1692d15d21a6f6,
          .dependencies = .{
              // See `zig fetch --save <url>` for a command-line interface for adding dependencies.
              .keylib = .{
                  .url = "https://github.com/Zig-Sec/keylib/archive/refs/tags/0.6.1.tar.gz",
                  // obtain a package matching this `hash`.
                  //
                  // Uses the [multihash](https://multiformats.io/multihash/) format.
                  .hash = "keylib-0.6.1-mbYjk9-WCQBOqB9oq2ZqWQFeWI2HwuBEuPgL-wkJDHTg",
              },
              .uuid = .{
                  .url = "https://github.com/r4gus/uuid-zig/archive/refs/tags/0.3.1.tar.gz",
                  .hash = "uuid-0.3.0-oOieIYF1AAA_BtE7FvVqqTn5uEYTvvz7ycuVnalCOf8C",
              },
              .ccdb = .{
                  .url = "https://github.com/r4gus/ccdb/archive/refs/tags/0.3.1.tar.gz",
                  .hash = "ccdb-0.3.2-mrOGYn4KDgC0cJl4CKpKaJB95wwIlHegHLV7NSbMYXu0",
              },
              .kdbx = .{
                  .url = "https://github.com/Zig-Sec/kdbx/archive/refs/tags/0.1.4.tar.gz",
                  .hash = "kdbx-0.1.4-eJXZBMa7CgAIw7kG02QYyv1sFcePsjfoGH9-Ptl3wrTC",
              },
          },
          // Specifies the set of files and directories that are included in this package.
          // Only files and directories listed here are included in the `hash` that
          // is computed for this package. Only files listed here will remain on disk
          // when using the zig package manager. As a rule of thumb, one should list
          // files required for compilation plus any license(s).
          // Paths are relative to the build root. Use the empty string (`""`) to refer to
          // the build root itself.
          // A directory listed here means that all files within, recursively, are included.
          .paths = .{
              "build.zig",
              "build.zig.zon",
              "linux",
              "README.md",
              "script",
              "src",
              "static",
          },
        }
        ZON
      end

      it "parses a ZON string into a Ruby object" do
        expected = {
          :name => :passkeez, 
          :version => "0.5.3", 
          :fingerprint => 0xdd1692d15d21a6f6,
          :dependencies => {
            :keylib => {
              :url => "https://github.com/Zig-Sec/keylib/archive/refs/tags/0.6.1.tar.gz",
              :hash => "keylib-0.6.1-mbYjk9-WCQBOqB9oq2ZqWQFeWI2HwuBEuPgL-wkJDHTg",
            },
            :uuid => {
              :url => "https://github.com/r4gus/uuid-zig/archive/refs/tags/0.3.1.tar.gz",
              :hash => "uuid-0.3.0-oOieIYF1AAA_BtE7FvVqqTn5uEYTvvz7ycuVnalCOf8C",
            },
            :ccdb => {
              :url => "https://github.com/r4gus/ccdb/archive/refs/tags/0.3.1.tar.gz",
              :hash => "ccdb-0.3.2-mrOGYn4KDgC0cJl4CKpKaJB95wwIlHegHLV7NSbMYXu0",
            },
            :kdbx => {
              :url => "https://github.com/Zig-Sec/kdbx/archive/refs/tags/0.1.4.tar.gz",
              :hash => "kdbx-0.1.4-eJXZBMa7CgAIw7kG02QYyv1sFcePsjfoGH9-Ptl3wrTC",
            },
          },
          :paths => [
            "build.zig",
            "build.zig.zon",
            "linux",
            "README.md",
            "script",
            "src",
            "static",
          ],
        }

        tokens = Lexer.parse @dict
        parser = Parser.new tokens

        obj = parser.parse

        expect(obj).to eq(expected)
      end

    end

end
